[package]
name = "somfy-protect-client"
version = "0.1.0"
authors = ["Jeremie Huchet"]
description = "Somfy Protect API client"
license = "GPL-3.0"
edition = "2021"

[dependencies]
log = "^0.4"
oauth2 = "^4.3"
reqwest = { version = "^0.11", features = ["json", "multipart"] }
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
somfy-protect-openapi = { path = "../somfy-protect-openapi" }
tokio = { version = "^1.28", features = ["rt"] }
url = "^2.2"
uuid = { version = "^1.0", features = ["serde"] }

[dev-dependencies]
httpmock = "^0.6"
tokio = "^1.28"